import { ThemeProvider } from "@/components/shared/ThemeProvider";
import Navbar from "@/components/shared/shell/Navbar";
import Topbar from "@/components/shared/shell/Topbar";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import ReduxProvider from "@/store/ReduxProvider";
import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Spendy",
  description: "Generated by create next app",
};

// export const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });
export const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});
// export const roboto = Roboto({
//   weight: ["400", "700"],
//   style: ["normal", "italic"],
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-sans",
// });

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            poppins.variable
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Topbar />
            <div className="flex gap-8">
              <Navbar />
              {children}
            </div>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ReduxProvider>
  );
}
